### ISSUE TITLE
Roundrobin pacemaker not working - Not always rotating

### ISSUE THREAD

**Issue by Raycoms** [hot-stuff/libhotstuff#10]
Hi, I ran hotstuff with the pacemaker rr, but the leader position stayed at position 0 over the entire livecycle.
Is there anything else that has to be configured for this?

**Comment by Raycoms** [comment]
```
    protected:
    void on_consensus(const block_t &blk) override {
        timer.del();
        exp_timeout = base_timeout;
        if (prop_blk[proposer] == blk) {
            stop_rotate();
        }
        else if (!rotating) {
            rotate();
        }
    }
```

I tried this to regularly rotate. But doing that kinda deteriorates the performance.
(37 consensus per minute) instead of thousands.

**Comment by Raycoms** [comment]
It is rotating on failure. But as described in the paper, it should possibly rotate every round even on success. How do I achieve this?

**Comment by Raycoms** [comment]
Any news on this?

**Comment by Determinant** [comment]
The built-in RR example is doing something similar to what PBFT does -- only rotate on faulty leader (which is the example given by the paper). In the paper, the core HotStuff logic does not require rotation on every success. Feel free to implement your own rotation mechanism as it is the primary goal of having such separate notion of a Pacemaker.
