### ISSUE TITLE
Chained HotStuff

### ISSUE THREAD

**Issue by Raycoms** [hot-stuff/libhotstuff#11]
I'm currently wondering, is the default implementation using the chained mode?
Because I'm seeing a block being committed on every quorum.

**Comment by Determinant** [comment]
There is only one "mode" in implementation. I don't why but it's kinda interesting that people tend to ignore the most important pseudocode in our paper. Actually, that "even-driven" one was the first pseudocode I drafted and all the preceding ones are just for academic/theoretical purpose.
