### ISSUE TITLE
about deploy

### ISSUE THREAD

**Issue by guokaiwen** [hot-stuff/libhotstuff#12]
when I reproduce your basic results, I used four EC2 with Ubuntu 18.04. But when I run ./run.sh new myrun1, there is a mistake said  # start the hotstuff replica **********************************************************************************************
  * replica2                   - FAILED!!! ------------------------------------------------------
    Unable to import hotstuff_app due to invalid syntax
  * replica1                   - FAILED!!! ------------------------------------------------------
    Unable to import hotstuff_app due to invalid syntax
  * replica0                   - FAILED!!! ------------------------------------------------------
    Unable to import hotstuff_app due to invalid syntax
.
# start the hotstuff replica **********************************************************************************************
  * replica3                   - FAILED!!! ------------------------------------------------------
    Unable to import hotstuff_app due to invalid syntax

# STATS *******************************************************************************************************************
localhost    : ok=7	changed=0	failed=0	unreachable=0	rescued=0	ignored=0
replica0    : ok=5	changed=4	failed=1	unreachable=0	rescued=0	ignored=0
replica1    : ok=5	changed=4	failed=1	unreachable=0	rescued=0	ignored=0
replica2    : ok=5	changed=4	failed=1	unreachable=0	rescued=0	ignored=0
replica3    : ok=5	changed=4	failed=1	unreachable=0	rescued=0	ignored=0

So what's going wrong?

**Comment by Determinant** [comment]
Seems like a python import error: probably you didn't have Python3?

**Comment by seafooler** [comment]
Have you solved this problem? I encountered it too. :(

**Comment by Determinant** [comment]
Close because there is no response. Reopen it if there is any progress.

**Comment by aqlangela** [comment]
Ran into the same problem and solved it by changing the installation of ansible that works with python2.7 to python3.
