### ISSUE TITLE
Failure on large deployments.

### ISSUE THREAD

**Issue by Raycoms** [hot-stuff/libhotstuff#13]
It seems that running this with > 250 processes the communication library starts breaking apart badly. It seems to fail to initiate all necessary connections and then errors out on the stats message.
Even wrapping this in a catch doesn't allow me to run it.

**Comment by Determinant** [comment]
The same library was used to run 2000 nodes for my paper. Not sure about the issue you're having here due to the limited information here.

**Comment by Raycoms** [comment]
For me salticidae was not able to keep up the all-to-all connection above 300 processes. I had to start setting up the connections only on demand.
