### ISSUE TITLE
Payload size

### ISSUE THREAD

**Issue by rk784893353** [hot-stuff/libhotstuff#15]
Hi,

I have deployed Hotstuff in AWS successfully, but I did not find a place to set payload size. 
I am not sure that it is the right way to define HOTSTUFF_CMD_REQSIZE and HOTSTUFF_CMD_RESPSIZE in client.h. When I set these two values as 1024 bytes, the client seemed unable to send requests to the replicas.

**Comment by Determinant** [comment]
Yeah those two should be the parameters to adjust. This issue might be caused by the introduced message size checking in salticidae. I'll try to reproduce this locally on my machine.

**Comment by Determinant** [comment]
Looks like it is triggered when `HOTSTUFF_CMD_RESPSIZE` is large. The issue is I forgot to reset the maximum message size setting at client side.

**Comment by Determinant** [comment]
Could you try out the fix (which is the latest master branch)?

**Comment by rk784893353** [comment]
Thanks a lot, it works! 
I have also successfully run the instance of 1024 bytes by modifying the network.h in salticidae.
