### ISSUE TITLE
Connection Losses when sending high quantities of data shortly after another

### ISSUE THREAD

**Issue by Raycoms** [hot-stuff/libhotstuff#16]
I've noticed that when CPU spikes happen a lot of connections break up and I also get strange error messages as:

```
2021-02-08 22:59:58.014039 [net info] send(89) failure: Success
2021-02-08 22:59:58.014100 [net info] send(89) failure: Success
```

```
2021-02-08 22:59:58.014155 [net info] 85f483e8f5: lost connection <Conn fd=89 addr=<NetAddr 10.1.0.57:20001> mode=active>
2021-02-08 22:59:58.014179 [net info] ended 85f483e8f5 <-/-> ae0d049455 (via <Conn fd=89 addr=<NetAddr 10.1.0.57:20001> mode=active>)
```

It doesn't say anything about the reason of the connection losses either. Is there a way to mitigate that?
It's strange to handle because data gets lost.

**Comment by Raycoms** [comment]
Disabling ssl does not solve the problem as a short side note.

**Comment by Raycoms** [comment]
Further observation: I called multicast in 10ms intervals, 10 times. Only 60ms after the last time send was called. But, some data didn't make it and the connection was reset (I believe due to buffer issues).

**Comment by Raycoms** [comment]
This should be possible to reproduce by sending 1 single block of 4000 ops (this is roughly a 1mb block, so that shouldn't be out of scope given that that's what a lot of blockchains assume)

**Comment by Raycoms** [comment]
Fixed in: https://github.com/Determinant/salticidae/pull/10

**Comment by Determinant** [comment]
Thanks for reporting this! I think we may have located why it caused this issue and fix it there.
