### ISSUE TITLE
[question] vheight is never updated

### ISSUE THREAD

**Issue by zhiqiangxu** [hot-stuff/libhotstuff#17]
vheight matters for safety, but it's never updated, so I doubt that safety is violated

**Comment by Determinant** [comment]
I'm not sure what you mean. Did you read the code? For example: https://github.com/hot-stuff/libhotstuff/blob/master/src/consensus.cpp#L199

**Comment by zhiqiangxu** [comment]
Oh, it just didn't show up when searching "vheight" in this project..

However it seems the implementation is treating block number as view number, won't this cause liveness problem?

**Comment by Determinant** [comment]
Please refer to the paper (https://arxiv.org/pdf/1803.05069.pdf). The implementation is based on the "event-driven HotStuff".

**Comment by zhiqiangxu** [comment]
I just notice there're some subtle difference between the 2019 and 2021 version.

The only question left is about the assumption of hot stuff, it assumes that a proposer for a level/height is uniquely decidable by all honest nodes, however practically this assumption can only hold if validators never change, otherwise the proposer for a level/height will depend on the branch chosen,  as the validator set can be changed at any level/height.

**Comment by Determinant** [comment]
I'm not quite sure what you mean: the latest version was finalized in 2019 (both PODC and arxiv. There is no such thing called "2021" version.)
`[v6] Tue, 23 Jul 2019 05:19:36 UTC (1,704 KB)`

Again, please read the paper.

**Comment by zhiqiangxu** [comment]
https://arxiv.org/pdf/1803.05069v1.pdf

The 2021 version is this on the top near the title :

`February 26, 2021`

But I just notices there's another date on the left side:

`13 Mar 2018`

**Comment by Determinant** [comment]
I'm not sure what you're getting at. That's the initial draft which describes an old version of the protocol (and it wasn't correct in its claims). The watermark shows it was uploaded in Mar 2018. You should not read that revision as the protocol was redesigned from scratch (with the same inspiration from the earlier idea).

**Comment by zhiqiangxu** [comment]
I'm very concerned with the correctness when validators can change at any height, in fact I developed an variant of hotstuff which mainly to overcome this problem: https://github.com/zhiqiangxu/bihs

**Comment by Determinant** [comment]
This is called *reconfiguration*. It is a separate problem from the consensus. A typical way is to use `consensus` to reconfigure itself. Please do more reading in literature of distributed systems.

**Comment by zhiqiangxu** [comment]
Thanks for clarification, it's an ingenious algorithm!
