### ISSUE TITLE
about implementation

### ISSUE THREAD

**Issue by seafooler** [hot-stuff/libhotstuff#19]
I have a confusion about the implementation.
Since C++11 has implemented `Promise` features/functions, why do the authors implement a new one in the include/hotstuff/promise.hpp file?

Could anyone help me to clear my confusion? Thanks a lot!

**Comment by Determinant** [comment]
The promise in C++11 is very limited as it doesn't have "chainable" semantics like the one in Javascript (or other languages). Fundamentally, the C++11 promise still uses thread-model, whereas what we would like here is event-driven model. (See https://paoloseverini.wordpress.com/2014/04/07/concurrency-in-c11/)
