### ISSUE TITLE
[Question] Can a malicious proposer cause an infinite non-deciding scenario in 'Basic HotStuff'

### ISSUE THREAD

**Issue by andrewnguyen22** [hot-stuff/libhotstuff#20]
The paper [BFT Consensus in the Lens of Blockchain][1] describes an infinite non-deciding scenario for a theoretical “two-phase” Hotstuff variant. Specifically, the [claim][2] is that the addition of a "precursor" voting round ensures that (n-f) participants know of any 'hidden/missing Lock' and a correct leader would be able to propose a value that all honest participants would accept without waiting the maximum network delay (such as Tendermint / Casper FFG). 

During this precursor round, if a quorum is achieved and a certificate is created, Replicas will store the highest Precursor (PrepareQC) they know of in a local variable known as **HighQC**. 

The paper details a '**SafeNodePredicate**' Replicas use to determine whether or not to accept a Proposal from a Leader.

[![SafeNodePredicate][3]][3]

However, within the **SafeNodePredicate** the **HighQC** (highest Precursor) of any Replica is never checked against the proposal. Could a malicious Proposer simply choose to ignore a **HighQC** removing the safety properties of the Precursor round and forcing a 'Hidden Lock'?

  [1]: https://arxiv.org/pdf/1803.05069.pdf
  [2]: https://youtu.be/ONobI3X70Rc?t=1337
  [3]: https://i.stack.imgur.com/IwWLc.png

**Comment by Determinant** [comment]
Malicious proposer can do whatever it wants at the protocol level. HighQC is only a local information derived by each correct replica and there is no need for "checking" it (I'm not quite sure about your question, though) as it is private. The quorum argument in the additional step (3-step HS) is used to guarantee the HighQC is correctly synced for the next correct proposer, regardless of other Byzantine nodes.

**Comment by andrewnguyen22** [comment]
Hey @Determinant thank you very much for the response! I appreciate your time

You are correct that I am looking at basic_hotstuff (which is theoretical)

#### To clarify the question: 

Other than `Optimistic Responsiveness` and ensuring the `Correct HighQC for a *Correct* Proposer`, is there any security justification for 3rd round of Basic Hotstuff?

Not criticizing, just trying to better understand the nuances of the 3rd step of Hotstuff. 

I would really appreciate a follow up!
