### ISSUE TITLE
build error on CentOS 7

### ISSUE THREAD

**Issue by pingxab** [hot-stuff/libhotstuff#25]
Env:
CentOS Linux release 7.6.1810 (Core)
cmake 3.11.0-1.el7
gcc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)
openssl 1.1.1l

cmake with the following error @Determinant 
```
[apps@mwpl71957 libhotstuff]$ cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED=ON -DHOTSTUFF_PROTO_LOG=ON
-- Found OpenSSL: /usr/lib64/libcrypto.so (found suitable version "1.1.1l", minimum required is "1.1.0") 
-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.1.1l") 
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.5") found components:  doxygen missing components:  dot
-- Configuring done
CMake Error in CMakeLists.txt:
  Target "hotstuff" requires the language dialect "CXX17" (with compiler
  extensions), but CMake does not know the compile flags to use to enable it.


CMake Error in CMakeLists.txt:
  Target "hotstuff_shared" requires the language dialect "CXX17" (with
  compiler extensions), but CMake does not know the compile flags to use to
  enable it.


CMake Error in CMakeLists.txt:
  Target "hotstuff_static" requires the language dialect "CXX17" (with
  compiler extensions), but CMake does not know the compile flags to use to
  enable it.


CMake Error in CMakeLists.txt:
  Target "hotstuff-tls-keygen" requires the language dialect "CXX17" (with
  compiler extensions), but CMake does not know the compile flags to use to
  enable it.


CMake Error in CMakeLists.txt:
  Target "hotstuff-keygen" requires the language dialect "CXX17" (with
  compiler extensions), but CMake does not know the compile flags to use to
  enable it.


CMake Error in test/CMakeLists.txt:
  Target "test_secp256k1" requires the language dialect "CXX17" (with
  compiler extensions), but CMake does not know the compile flags to use to
  enable it.


CMake Error in examples/CMakeLists.txt:
  Target "hotstuff-client" requires the language dialect "CXX17" (with
  compiler extensions), but CMake does not know the compile flags to use to
  enable it.


CMake Error in examples/CMakeLists.txt:
  Target "hotstuff-app" requires the language dialect "CXX17" (with compiler
  extensions), but CMake does not know the compile flags to use to enable it.


-- Generating done
-- Build files have been written to: /apps/tmp/libhotstuff
```

**Comment by pingxab** [comment]
make with the following error
![image](https://user-images.githubusercontent.com/5651810/154200443-280ae7ed-a4c9-4020-90aa-bccda16f8ff1.png)

**Comment by pingxab** [comment]
> Env: CentOS Linux release 7.6.1810 (Core) cmake 3.11.0-1.el7 gcc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2) openssl 1.1.1l
> 
> cmake with the following error @Determinant
> 
> ```
> [apps@mwpl71957 libhotstuff]$ cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED=ON -DHOTSTUFF_PROTO_LOG=ON
> -- Found OpenSSL: /usr/lib64/libcrypto.so (found suitable version "1.1.1l", minimum required is "1.1.0") 
> -- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.1.1l") 
> -- Found Doxygen: /usr/bin/doxygen (found version "1.8.5") found components:  doxygen missing components:  dot
> -- Configuring done
> CMake Error in CMakeLists.txt:
>   Target "hotstuff" requires the language dialect "CXX17" (with compiler
>   extensions), but CMake does not know the compile flags to use to enable it.
> 
> 
> CMake Error in CMakeLists.txt:
>   Target "hotstuff_shared" requires the language dialect "CXX17" (with
>   compiler extensions), but CMake does not know the compile flags to use to
>   enable it.
> 
> 
> CMake Error in CMakeLists.txt:
>   Target "hotstuff_static" requires the language dialect "CXX17" (with
>   compiler extensions), but CMake does not know the compile flags to use to
>   enable it.
> 
> 
> CMake Error in CMakeLists.txt:
>   Target "hotstuff-tls-keygen" requires the language dialect "CXX17" (with
>   compiler extensions), but CMake does not know the compile flags to use to
>   enable it.
> 
> 
> CMake Error in CMakeLists.txt:
>   Target "hotstuff-keygen" requires the language dialect "CXX17" (with
>   compiler extensions), but CMake does not know the compile flags to use to
>   enable it.
> 
> 
> CMake Error in test/CMakeLists.txt:
>   Target "test_secp256k1" requires the language dialect "CXX17" (with
>   compiler extensions), but CMake does not know the compile flags to use to
>   enable it.
> 
> 
> CMake Error in examples/CMakeLists.txt:
>   Target "hotstuff-client" requires the language dialect "CXX17" (with
>   compiler extensions), but CMake does not know the compile flags to use to
>   enable it.
> 
> 
> CMake Error in examples/CMakeLists.txt:
>   Target "hotstuff-app" requires the language dialect "CXX17" (with compiler
>   extensions), but CMake does not know the compile flags to use to enable it.
> 
> 
> -- Generating done
> -- Build files have been written to: /apps/tmp/libhotstuff
> ```

the above error is fixed by removing my gcc compilers(OS original 4.8.5, newly installed gcc 9.3.1 under /opt/rh/devtoolset-9), and when I link 
ln -s /opt/rh/devtoolset-9/root/bin/c++ /usr/bin/c++
sudo ln -s /opt/rh/devtoolset-9/root/bin/cc /usr/bin/cc
the cmake issue went away, Now I'm still stuck in the make error , the last step to compile libsecp256k1, seems related also to my environment.

**Comment by chenqping** [comment]
> Env: CentOS Linux release 7.6.1810 (Core) cmake 3.11.0-1.el7 gcc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2) openssl 1.1.1l
> 
> cmake with the following error @Determinant
> 
> ```
> [apps@mwpl71957 libhotstuff]$ cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED=ON -DHOTSTUFF_PROTO_LOG=ON
> -- Found OpenSSL: /usr/lib64/libcrypto.so (found suitable version "1.1.1l", minimum required is "1.1.0") 
> -- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.1.1l") 
> -- Found Doxygen: /usr/bin/doxygen (found version "1.8.5") found components:  doxygen missing components:  dot
> -- Configuring done
> CMake Error in CMakeLists.txt:
>   Target "hotstuff" requires the language dialect "CXX17" (with compiler
>   extensions), but CMake does not know the compile flags to use to enable it.
> 
> 
> CMake Error in CMakeLists.txt:
>   Target "hotstuff_shared" requires the language dialect "CXX17" (with
>   compiler extensions), but CMake does not know the compile flags to use to
>   enable it.
> 
> 
> CMake Error in CMakeLists.txt:
>   Target "hotstuff_static" requires the language dialect "CXX17" (with
>   compiler extensions), but CMake does not know the compile flags to use to
>   enable it.
> 
> 
> CMake Error in CMakeLists.txt:
>   Target "hotstuff-tls-keygen" requires the language dialect "CXX17" (with
>   compiler extensions), but CMake does not know the compile flags to use to
>   enable it.
> 
> 
> CMake Error in CMakeLists.txt:
>   Target "hotstuff-keygen" requires the language dialect "CXX17" (with
>   compiler extensions), but CMake does not know the compile flags to use to
>   enable it.
> 
> 
> CMake Error in test/CMakeLists.txt:
>   Target "test_secp256k1" requires the language dialect "CXX17" (with
>   compiler extensions), but CMake does not know the compile flags to use to
>   enable it.
> 
> 
> CMake Error in examples/CMakeLists.txt:
>   Target "hotstuff-client" requires the language dialect "CXX17" (with
>   compiler extensions), but CMake does not know the compile flags to use to
>   enable it.
> 
> 
> CMake Error in examples/CMakeLists.txt:
>   Target "hotstuff-app" requires the language dialect "CXX17" (with compiler
>   extensions), but CMake does not know the compile flags to use to enable it.
> 
> 
> -- Generating done
> -- Build files have been written to: /apps/tmp/libhotstuff
> ```

the above error is fixed by removing my gcc compilers(OS original 4.8.5, newly installed gcc 9.3.1 under /opt/rh/devtoolset-9), and when I link 
ln -s /opt/rh/devtoolset-9/root/bin/c++ /usr/bin/c++
sudo ln -s /opt/rh/devtoolset-9/root/bin/cc /usr/bin/cc
the cmake issue went away, Now I'm still stuck in the make error , the last step to compile libsecp256k1, seems related also to my environment.
